server:
  port: 8088

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://192.168.148.130:3306/pointsmanager?characterEncoding=UTF-8&useUnicode=true

#自定义配置参数
myscore:
  imgPath: /Library/apache-tomcat-7.0.70/webapps/zlj/
  imgDictory: static/

wechatConfig:
  corpId: wxe83ec6aeca12528c
  agentId: 1000010
  secret: tIXgd31c8nLbcawmeDSaasStceZ_X-HVXZBXGqxQhx0
  redirectUrl: http://weixin.shidanli.cn:8081/zlj/mobile/index.html?gameId=GAMEID
